language: java
jdk:
  - oraclejdk8
env:
  - AUTH0_PROPERTIES=C:\\Users\\Asistente\\Documents\\NetBeansProjects\\auth0_artwork\\artwork-api\\src\\main\\java\\co\\edu\\uniandes\\csw\\auth\\properties\\auth0.properties
after_success:
  - mvn sonar:sonar
